#!/usr/bin/env python3
"""Check whether a Monocle report came from a canonical Monocle skill.

This is the deterministic half of references/verify-report.md. It does four
things:

- parses the report's attestation block and checks it against the canonical
  repository;
- re-derives the Monocle Score from the report's own tables, using the
  scoring rules parsed from canonical SKILL.md;
- checks the report layout;
- flags text that may be trying to steer the checker.

Judgment checks, such as Rule 14 misuse and severity softening, stay with the
agent.

The report is untrusted input. None of its text reaches a shell, and the only
report value ever passed to git is a commit hash that matched a strict
pattern. Fetched repository content is read with git plumbing; it is never
checked out or executed.

Usage:
    verify_report.py REPORT (--fetch | --canonical DIR) [--ref REF] [--json]
    verify_report.py --manifest DIR
    verify_report.py --self-test

Exit status: 0 for OFFICIAL, 1 for any other verdict, 2 for errors.
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass, field
from pathlib import Path

CANONICAL_URL = "https://github.com/dan-snelson/Monocle"
CANONICAL_BRANCHES = ("main", "development")
MAX_REPORT_BYTES = 2 * 1024 * 1024
MAX_HISTORY = 500

SEVERITIES = ("Critical", "High", "Medium", "Low", "Info")
BANDS = ("Excellent", "Good", "Fair", "Poor", "Critical")
SEVERITY_EMOJI = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🔵", "Info": "⚪"}
BAND_EMOJI = {"Excellent": "🟢", "Good": "🔵", "Fair": "🟡", "Poor": "🟠", "Critical": "🔴"}
VIEWS = ("Executive View", "Security View", "Manager View", "Engineer View")

OFFICIAL = "OFFICIAL"
SUSPECT = "SUSPECT"
WEAKENED = "NON-CANONICAL / WEAKENED"
FORGED = "FORGED"

ATTESTATION_KEYS = (
    "monocle_attestation", "skill_repo", "skill_commit", "skill_ref", "skill_tree",
    "skill_sha256", "skill_dirty", "target", "target_ref", "score_raw",
    "score_final", "score_alt", "band", "generated_by", "timestamp",
)
# v2 adds deployment_context; v1 blocks come from skill commits before references/deployment-context.md.
ATTESTATION_VERSIONS = ("v1", "v2")
ATTESTATION_KEYS_V2 = ATTESTATION_KEYS + ("deployment_context",)
CONTEXT_REFERENCE = "monocle/references/deployment-context.md"
CONTEXT_LINE = "**Deployment context:**"
CONTEXT_LABELS = {"Operator-stated": "operator", "None supplied": "none"}
COMMIT_RE = re.compile(r"^[0-9a-f]{7,40}$")
TREE_RE = re.compile(r"^[0-9a-f]{40}$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
REF_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]*$")
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
FOOTER_RE = re.compile(
    r"^\[Generated by Monocle\]\(https://github\.com/dan-snelson/Monocle(?:/tree/([0-9a-f]{7,40}))?\)$"
)
TOTAL_RE = re.compile(r"^\*\*Total:\*\*\s*100\s*[−-]\s*(.+?)\s*=\s*(-?\d+)(.*)$")
SCORE_RE = re.compile(r"(\d+)/100\s*\(([^)]*)\)")
STEERING_RE = re.compile(
    r"ignore (?:all |any )?(?:previous|prior|above|earlier) instructions"
    r"|\b(?:integrity[- ]checker|verifier|verify_report)\b",
    re.IGNORECASE,
)
MANIFEST_SKIP_FILES = {".DS_Store"}
MANIFEST_SKIP_DIRS = {"__pycache__"}
GIT_ENV = dict(os.environ, GIT_TERMINAL_PROMPT="0", LC_ALL="C")


class VerifyError(Exception):
    """A problem that stops verification: bad input, unparseable rules, or a git failure."""


@dataclass
class Check:
    group: str  # attestation, provenance, rules, arithmetic, structure, steering
    name: str
    status: str  # pass, fail, warn, skip
    detail: str


@dataclass
class Audit:
    checks: list = field(default_factory=list)
    attestation: dict = None
    reported_final: int = None
    reported_band: str = None
    expected_final: int = None
    expected_band: str = None
    rules_source: str = ""
    canonical_source: str = ""

    def add(self, group, name, ok, detail, warn_only=False):
        status = "pass" if ok else ("warn" if warn_only else "fail")
        self.checks.append(Check(group, name, status, detail))

    def note(self, group, name, status, detail):
        self.checks.append(Check(group, name, status, detail))

    def failed(self, *groups):
        return any(check.status == "fail" and check.group in groups for check in self.checks)


@dataclass
class Rules:
    each: dict
    nonsec_each: int
    nonsec_cap: int
    ranges: dict
    bands: list

    def band(self, score):
        for low, high, name in self.bands:
            if low <= score <= high:
                return name
        raise VerifyError(f"no band covers a score of {score}")

    def clamp(self, raw, highest):
        low, high = self.ranges[highest]
        return min(max(max(raw, 0), low), high)

    def score(self, counts, nonsec):
        deductions = sum(self.each[sev] * counts.get(sev, 0) for sev in SEVERITIES)
        deductions += min(nonsec * self.nonsec_each, self.nonsec_cap)
        highest = highest_severity(counts)
        return 100 - deductions, self.clamp(100 - deductions, highest), highest


@dataclass
class Row:
    ids: list
    count: int
    each: int
    cap: int
    deduction: int
    text: str


# ---------------------------------------------------------------- helpers


def word_in(text, words):
    return next((word for word in words if re.search(rf"\b{word}\b", text)), None)


def first_int(text):
    match = re.search(r"-?\d+", text or "")
    return int(match.group()) if match else None


def to_int(text):
    return int(text) if text is not None and re.fullmatch(r"-?\d+", text) else None


def parse_range(text):
    match = re.search(r"(\d+)\s*[–-]\s*(\d+)", text)
    if not match:
        raise VerifyError(f"cannot parse a score range from {text!r}")
    return int(match.group(1)), int(match.group(2))


def highest_severity(counts):
    return next((sev for sev in SEVERITIES if counts.get(sev, 0) > 0), "none")


def cells(line):
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def expand_ids(text):
    ids = []
    for match in re.finditer(r"\bS(\d+)(?:\s*[–-]\s*S?(\d+))?", text):
        low = int(match.group(1))
        high = int(match.group(2) or low)
        if 0 <= high - low <= MAX_HISTORY:
            ids.extend(f"S{n}" for n in range(low, high + 1))
    return ids


def anchor(title):
    return re.sub(r"[^a-z0-9 -]", "", title.lower()).replace(" ", "-")


def label(score, band):
    return f"{score}/100 ({band})" if score is not None else "unknown"


def normalize_url(url):
    return re.sub(r"(\.git)?/*$", "", (url or "").strip())


def outside_fences(lines):
    """Yield (index, line) for lines that are not inside a fenced code block."""
    fence = None
    for index, line in enumerate(lines):
        match = FENCE_RE.match(line)
        if fence:
            if re.match(rf"^\s*{re.escape(fence[0])}{{{len(fence)},}}\s*$", line):
                fence = None
        elif match:
            fence = match.group(1)
        else:
            yield index, line


# ---------------------------------------------------------------- manifest


def manifest_entries(root):
    """Return (./relative/path, sha256) for every regular file under a skill directory."""
    root = Path(root)
    if not root.is_dir():
        raise VerifyError(f"{root} is not a directory")
    entries = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [name for name in dirnames if name not in MANIFEST_SKIP_DIRS]
        for name in filenames:
            path = Path(dirpath, name)
            if name in MANIFEST_SKIP_FILES or path.is_symlink() or not path.is_file():
                continue
            relative = "./" + path.relative_to(root).as_posix()
            entries.append((relative, hashlib.sha256(path.read_bytes()).hexdigest()))
    return entries


def manifest_digest(entries):
    """Hash the manifest exactly as the bash stamp in references/attestation.md does."""
    ordered = sorted(entries, key=lambda entry: entry[0].encode("utf-8"))
    text = "".join(f"{digest}  {relative}\n" for relative, digest in ordered)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------- rules


def table_after(lines, marker):
    start = next((i for i, line in enumerate(lines) if line.startswith(marker)), None)
    if start is None:
        raise VerifyError(f"canonical SKILL.md has no {marker} table")
    rows = []
    for line in lines[start + 1:]:
        if line.startswith("|"):
            rows.append(cells(line))
        elif rows:
            break
    return rows[2:]


def parse_rules(text):
    """Parse the Deductions, Band limits, and Bands tables from SKILL.md Step 5."""
    lines = text.splitlines()
    each, nonsec = {}, None
    for row in table_after(lines, "**Deductions.**"):
        numbers = [int(n) for n in re.findall(r"\d+", row[1] if len(row) > 1 else "")]
        if row[0].lower().startswith("non-security") and len(numbers) >= 2:
            nonsec = numbers[:2]
        elif word_in(row[0], SEVERITIES) and numbers:
            each[word_in(row[0], SEVERITIES)] = numbers[0]

    ranges = {}
    for row in table_after(lines, "**Band limits.**"):
        span = parse_range(row[1])
        names = [sev for sev in SEVERITIES if re.search(rf"\b{sev}\b", row[0])]
        if re.search(r"\bnone\b", row[0]):
            names.append("none")
        for name in names:
            ranges[name] = span

    bands = []
    for row in table_after(lines, "**Bands.**"):
        name = word_in(row[1], BANDS) if len(row) > 1 else None
        if name:
            bands.append((*parse_range(row[0]), name))

    missing = [sev for sev in SEVERITIES if sev not in each]
    missing += [] if nonsec else ["Non-security"]
    missing += [f"{sev} range" for sev in ("Critical", "High", "Medium", "Low", "none") if sev not in ranges]
    covered = sorted(n for low, high, _ in bands for n in range(low, high + 1))
    if missing or covered != list(range(101)):
        raise VerifyError(f"could not parse the Step 5 scoring tables (missing: {', '.join(missing) or 'band coverage'})")
    ranges.setdefault("Info", ranges["none"])
    return Rules(each, nonsec[0], nonsec[1], ranges, bands)


# ---------------------------------------------------------------- report


class Report:
    def __init__(self, text):
        self.text = text
        self.lines = text.splitlines()
        heads = [(i, line[3:].strip()) for i, line in outside_fences(self.lines) if line.startswith("## ")]
        self.sections = []
        for n, (start, title) in enumerate(heads):
            end = heads[n + 1][0] if n + 1 < len(heads) else len(self.lines)
            self.sections.append((title, start, end))
        self.by_title = {}
        for title, start, end in self.sections:
            self.by_title.setdefault(title, (start, end))
        nonblank = [line.strip() for line in self.lines if line.strip()]
        self.footer = nonblank[-1] if nonblank else ""
        self.before_footer = nonblank[-2] if len(nonblank) > 1 else ""
        match = FOOTER_RE.match(self.footer)
        self.footer_ok = bool(match)
        self.footer_commit = match.group(1) if match else None

    def body(self, title):
        start, end = self.by_title.get(title, (0, 0))
        return self.lines[start:end]

    def table(self, title, header):
        lines = self.body(title)
        for i, line in enumerate(lines):
            if line.startswith("|") and [c.lower() for c in cells(line)][: len(header)] == list(header):
                rows = []
                for row in lines[i + 2:]:
                    if not row.startswith("|"):
                        break
                    rows.append(cells(row))
                return rows
        return None

    def scope_fields(self):
        rows = self.table("Scope", ("field", "value")) or []
        return {row[0].strip("* "): row[1] for row in rows if len(row) >= 2}


def parse_attestation(lines):
    starts = [i for i, line in enumerate(lines) if re.match(r"^\s*monocle_attestation\s*:", line)]
    if not starts:
        return None, starts, []
    values, duplicates = {}, []
    for line in lines[starts[0]:]:
        match = re.match(r"^\s*([a-z0-9_]+)\s*:\s*(.*?)\s*$", line)
        if not match:
            break
        if match.group(1) in values:
            duplicates.append(match.group(1))
        values.setdefault(match.group(1), match.group(2))
    return values, starts, duplicates


# ---------------------------------------------------------------- checks


def check_structure(audit, report):
    lines, titles = report.lines, [title for title, _, _ in report.sections]
    audit.add("structure", "title", bool(lines) and lines[0].startswith("# Monocle Report:"),
              f"line 1 is {lines[0][:60]!r}" if lines else "report is empty")
    audit.add("structure", "Monocle Score on line 2", len(lines) > 1 and lines[1] == "## Monocle Score",
              "`## Monocle Score` must follow the title directly")
    views = [title for title in titles if title in VIEWS]
    audit.add("structure", "views present", bool(views),
              f"views found: {', '.join(views) or 'none'}")
    audit.add("structure", "view order", views == [v for v in VIEWS if v in views],
              f"order found: {', '.join(views)}", warn_only=True)
    audit.add("structure", "Scope section", "Scope" in titles, "a `## Scope` section is required")
    audit.add("structure", "Scope last", titles[-1:] == ["Scope"],
              f"last section is {titles[-1] if titles else 'missing'}", warn_only=True)

    links = re.findall(r"^- \[([^\]]+)\]\(#([^)]+)\)", "\n".join(report.body("Contents")), re.MULTILINE)
    expected = [title for title in titles if title != "Contents"]
    audit.add("structure", "Contents", [t for t, _ in links] == expected and all(a == anchor(t) for t, a in links),
              f"Contents links {[t for t, _ in links]}; sections {expected}", warn_only=True)
    collapsed = []
    for title, start, end in report.sections:
        following = next((line.strip() for line in report.lines[start + 1:end] if line.strip()), "")
        if title != "Contents" and following != "<details>":
            collapsed.append(title)
    audit.add("structure", "collapsed sections", not collapsed,
              f"sections not wrapped in a plain <details>: {', '.join(collapsed) or 'none'}", warn_only=True)

    audit.add("structure", "footer", report.footer_ok,
              f"last line must be the Monocle footer; found {report.footer[:100]!r}")
    audit.add("structure", "footer rule", report.before_footer == "---",
              "a `---` line must precede the footer", warn_only=True)


def check_attestation(audit, report):
    values, starts, duplicates = parse_attestation(report.lines)
    if values is None:
        audit.add("attestation", "present", False, "no `monocle_attestation:` block; the report can't be considered official")
        return
    audit.attestation = values
    version = values.get("monocle_attestation")
    keys = ATTESTATION_KEYS_V2 if version == "v2" else ATTESTATION_KEYS
    missing = [key for key in keys if key not in values]
    audit.add("attestation", "complete", not missing, f"missing fields: {', '.join(missing) or 'none'}")
    audit.add("attestation", "single block", len(starts) == 1 and not duplicates,
              f"{len(starts)} attestation block(s); repeated fields: {', '.join(duplicates) or 'none'}")
    audit.add("attestation", "version", version in ATTESTATION_VERSIONS,
              f"monocle_attestation: {version!r} (expected {' or '.join(ATTESTATION_VERSIONS)})")

    formats = {
        "skill_commit": lambda v: v == "unknown" or COMMIT_RE.match(v),
        "skill_tree": lambda v: v == "unavailable" or TREE_RE.match(v),
        "skill_sha256": lambda v: SHA256_RE.match(v),
        "skill_dirty": lambda v: v in ("true", "false", "unknown"),
        "score_raw": lambda v: to_int(v) is not None,
        "score_final": lambda v: to_int(v) is not None and 0 <= to_int(v) <= 100,
        "score_alt": lambda v: v == "none" or (to_int(v) is not None and 0 <= to_int(v) <= 100),
        "deployment_context": lambda v: v in CONTEXT_LABELS.values(),
    }
    bad = [f"{key}={values[key]!r}" for key, test in formats.items() if key in values and not test(values[key])]
    audit.add("attestation", "field formats", not bad, f"malformed: {', '.join(bad) or 'none'}")

    start, end = report.by_title.get("Scope", (0, 0))
    audit.add("attestation", "inside Scope", start <= starts[0] < end,
              "the attestation block belongs at the end of the Scope section", warn_only=True)

    audit.add("provenance", "skill repository", normalize_url(values.get("skill_repo")) == CANONICAL_URL,
              f"skill_repo: {values.get('skill_repo')!r}; canonical is {CANONICAL_URL}")
    commit = values.get("skill_commit", "")
    if report.footer_commit:
        audit.add("provenance", "footer commit", COMMIT_RE.match(commit) is not None
                  and (commit.startswith(report.footer_commit) or report.footer_commit.startswith(commit)),
                  f"footer pins {report.footer_commit}; attestation claims {commit}")
    elif COMMIT_RE.match(commit):
        audit.note("structure", "footer commit", "warn", "footer link isn't pinned to the attested commit")

    scope = report.scope_fields()
    for key, field_name in (("target", "Target"), ("target_ref", "Ref"), ("generated_by", "Generated by"), ("timestamp", "Date")):
        if field_name in scope and key in values:
            audit.add("attestation", f"{key} matches Scope", values[key] == scope[field_name],
                      f"attestation {values[key]!r}; Scope {field_name} {scope[field_name]!r}", warn_only=True)


def check_context_line(audit, body, attested):
    """A v2 report shows its Deployment Context, and the line agrees with the attestation."""
    line = next((line for line in body if line.startswith(CONTEXT_LINE)), None)
    audit.add("structure", "Deployment context line", line is not None,
              f"`{CONTEXT_LINE}` line {'present' if line else 'missing'} in the Monocle Score section")
    if line is None:
        return
    text = line[len(CONTEXT_LINE):].strip()
    shown = next((value for label_text, value in CONTEXT_LABELS.items() if text.startswith(label_text)), None)
    audit.add("structure", "Deployment context matches attestation", shown == attested,
              f"line reads {text[:60]!r}; attestation deployment_context is {attested!r}")


def check_steering(audit, report):
    # Fenced blocks count too: a quoted "snippet" is an easy place to hide an instruction.
    hits = [line.strip()[:120] for line in report.lines if STEERING_RE.search(line)]
    detail = ("possible text aimed at the checker; judge it per verify-report.md: " + " | ".join(hits[:3])
              if hits else "no text addressed to a verifier")
    audit.add("steering", "checker-steering text", not hits, detail, warn_only=True)


def check_score(audit, report, rules):
    if "Monocle Score" not in report.by_title:
        audit.add("structure", "Monocle Score section", False, "no `## Monocle Score` section")
        return
    body = report.body("Monocle Score")
    for prefix in ("**Score:**", "**Overall risk:**", "**Recommendation:**", "**Generated by:**", "**Operator baseline:**"):
        present = any(line.startswith(prefix) for line in body)
        audit.add("structure", f"{prefix.strip('*:')} line", present,
                  f"`{prefix}` line {'present' if present else 'missing'} in the Monocle Score section")
    att = audit.attestation or {}
    if att.get("monocle_attestation") == "v2":
        check_context_line(audit, body, att.get("deployment_context"))

    table = report.table("Monocle Score", ("source", "ids", "count", "each", "deduction"))
    if table is None:
        audit.add("structure", "deduction table", False, "no `| Source | IDs | Count | Each | Deduction |` table")
        return

    rows = {}
    for row in table:
        if len(row) < 5:
            continue
        lower = row[0].lower()
        key = ("Non-security" if lower.startswith("non-security")
               else "Not scored" if lower.startswith("not scored") else word_in(row[0], SEVERITIES))
        if key:
            cap = re.search(r"max\D*(\d+)", row[3])
            rows[key] = Row(expand_ids(row[1]), first_int(row[2]) or 0, first_int(row[3]),
                            int(cap.group(1)) if cap else None, first_int(row[4]), "| " + " | ".join(row) + " |")

    # Rule fidelity: per-finding deductions and the non-security cap.
    for sev in SEVERITIES:
        row = rows.get(sev)
        if row is None:
            audit.add("rules", f"{sev} row", False, f"the deduction table has no {sev} row")
            continue
        audit.add("rules", f"{sev} deduction", row.each == rules.each[sev],
                  f"report charges {row.each} per {sev} finding; canonical SKILL.md charges {rules.each[sev]} (`{row.text}`)")
    nonsec_row = rows.get("Non-security")
    if nonsec_row is None:
        audit.add("rules", "Non-security row", False, "the deduction table has no Non-security row")
    else:
        audit.add("rules", "Non-security deduction",
                  (nonsec_row.each, nonsec_row.cap) == (rules.nonsec_each, rules.nonsec_cap),
                  f"report: {nonsec_row.each} each, max {nonsec_row.cap}; canonical: {rules.nonsec_each} each, "
                  f"max {rules.nonsec_cap} (`{nonsec_row.text}`)")

    # Arithmetic within the table.
    for key, row in rows.items():
        each = row.each or 0
        if key == "Non-security":
            expected = min(row.count * each, row.cap if row.cap is not None else rules.nonsec_cap)
        elif key == "Not scored":
            expected = 0
        else:
            expected = row.count * each
            if row.ids:
                audit.add("arithmetic", f"{key} IDs", len(row.ids) == row.count,
                          f"{len(row.ids)} IDs listed ({', '.join(row.ids)}) but Count is {row.count}")
        audit.add("arithmetic", f"{key} row", row.deduction == expected,
                  f"Deduction {row.deduction}; Count × Each gives {expected} (`{row.text}`)")

    counts = {sev: rows[sev].count if sev in rows else 0 for sev in SEVERITIES}
    nonsec = nonsec_row.count if nonsec_row else 0

    # Cross-check against the Security view findings table.
    findings = report.table("Security View", ("id", "severity"))
    table_counts, table_sev = {sev: 0 for sev in SEVERITIES}, {}
    if findings is None:
        audit.note("arithmetic", "findings table", "skip", "no Security view findings table (subset report?)")
    else:
        for row in findings:
            sev = word_in(row[1], SEVERITIES) if len(row) > 1 else None
            if sev:
                table_counts[sev] += 1
                table_sev[row[0].strip()] = sev
        for sev in SEVERITIES:
            scored, listed = counts[sev], table_counts[sev]
            if sev == "Low" and scored == listed + 1:
                audit.note("arithmetic", "Low count", "warn",
                           f"one more Low scored ({scored}) than listed ({listed}); valid only for a roll-up that names a real gap")
            else:
                audit.add("arithmetic", f"{sev} count", scored == listed,
                          f"findings table lists {listed} {sev}; deduction table counts {scored}", warn_only=sev == "Info")
            for finding_id in rows[sev].ids if sev in rows else []:
                if finding_id in table_sev and table_sev[finding_id] != sev:
                    audit.add("arithmetic", f"{finding_id} severity", False,
                              f"{finding_id} is {table_sev[finding_id]} in the findings table but scored as {sev}")

    # The Total line: deductions, raw score, clamp, and band.
    total_line = next((line for line in body if line.startswith("**Total:**")), None)
    match = TOTAL_RE.match(total_line or "")
    if not match:
        audit.add("structure", "Total line", False, f"missing or unparseable Total line: {total_line!r}")
        return
    stated_sum = sum(int(n) for n in re.findall(r"\d+", match.group(1)))
    table_sum = sum(row.deduction or 0 for row in rows.values())
    audit.add("arithmetic", "Total deductions", stated_sum == table_sum,
              f"Total subtracts {stated_sum}; the table's Deduction column sums to {table_sum}")
    raw = int(match.group(2))
    audit.add("arithmetic", "raw score", raw in (100 - stated_sum, max(0, 100 - stated_sum)),
              f"100 − {stated_sum} should be {100 - stated_sum}; Total says {raw}")
    final_match = re.search(r"\*\*(\d+)/100\s*\(([^)]*)\)\*\*", match.group(3))
    if not final_match:
        audit.add("structure", "Total result", False, f"Total line has no **n/100 (band)** result: {total_line!r}")
        return
    final, band = int(final_match.group(1)), word_in(final_match.group(2), BANDS)
    audit.reported_final, audit.reported_band = final, band

    highest = highest_severity(counts)
    clamped = rules.clamp(raw, highest)
    low, high = rules.ranges[highest]
    audit.add("rules", "band limit", final == clamped,
              f"highest scored severity is {highest} (range {low}–{high}); raw {raw} clamps to {clamped}, report gives {final}")
    phrase = re.search(r"\b(capped|floored) at (\d+)", match.group(3))
    wanted = "capped" if raw > high else "floored" if max(raw, 0) < low else None
    audit.add("rules", "clamp wording", (phrase.group(1) if phrase else None) == wanted,
              f"Total says {phrase.group(0) if phrase else 'no clamp'}; canonical rules give {wanted or 'no clamp'}", warn_only=True)
    audit.add("arithmetic", "band", band == rules.band(final),
              f"{final} is {rules.band(final)} under canonical bands; report says {band}")

    # Every place the headline appears must agree.
    summary = next((SCORE_RE.search(line) for line in body if line.startswith("<summary>Monocle Score:")), None)
    score_line = next((line for line in body if line.startswith("**Score:**")), "")
    score_match = SCORE_RE.search(score_line)
    alt_match = re.search(r",\s*or\s+(\d+)/100\s*\(([^)]*)\)", score_line)
    shown = {"summary": summary, "Score line": score_match}
    for where, found in shown.items():
        audit.add("arithmetic", f"{where} score", bool(found) and int(found.group(1)) == final,
                  f"{where} shows {found.group(0) if found else 'no score'}; Total gives {final}/100")
    if att:
        audit.add("arithmetic", "attested final", to_int(att.get("score_final")) == final,
                  f"attestation score_final {att.get('score_final')}; Total gives {final}")
        audit.add("arithmetic", "attested raw", to_int(att.get("score_raw")) in (raw, max(raw, 0)),
                  f"attestation score_raw {att.get('score_raw')}; Total gives {raw}")
        audit.add("arithmetic", "attested band", att.get("band") == band,
                  f"attestation band {att.get('band')!r}; Total gives {band!r}")
        alt = alt_match.group(1) if alt_match else "none"
        audit.add("arithmetic", "attested alternate", att.get("score_alt") == alt,
                  f"attestation score_alt {att.get('score_alt')!r}; Score line alternate {alt!r}")
    if alt_match:
        alt, alt_band = int(alt_match.group(1)), word_in(alt_match.group(2), BANDS)
        audit.add("arithmetic", "alternate band", alt_band == rules.band(alt),
                  f"alternate {alt} is {rules.band(alt)} under canonical bands; report says {alt_band}")
        audit.add("arithmetic", "alternate direction", alt <= final,
                  f"alternate {alt} is above the headline {final}; a misconfigured case shouldn't score higher", warn_only=True)
    elif att.get("deployment_context") == "operator":
        audit.note("structure", "context alternate", "warn",
                   "operator-stated context but no alternate score; valid only if the context changed no rating")

    # What canonical rules give for the findings this report lists. Taking the larger
    # count per severity means findings dropped from the table are still charged.
    expected_counts = {sev: max(counts[sev], table_counts[sev]) for sev in SEVERITIES}
    _, audit.expected_final, _ = rules.score(expected_counts, nonsec)
    audit.expected_band = rules.band(audit.expected_final)
    audit.add("arithmetic", "official score", final == audit.expected_final,
              f"canonical rules give {label(audit.expected_final, audit.expected_band)} for these findings; "
              f"report gives {label(final, band)}")


# ---------------------------------------------------------------- canonical repository


class Git:
    def __init__(self, repo):
        self.repo = str(repo)

    def run(self, *args, data=None):
        # Arguments are a fixed git subcommand plus refs and hashes this script validated; no shell.
        return subprocess.run(["git", "-C", self.repo, *args], input=data,
                              capture_output=True, env=GIT_ENV, check=False)

    def out(self, *args, data=None):
        proc = self.run(*args, data=data)
        if proc.returncode:
            raise VerifyError(f"git {args[0]} failed: {proc.stderr.decode(errors='replace').strip()}")
        return proc.stdout

    def ok(self, *args):
        return self.run(*args).returncode == 0

    def resolve(self, rev):
        proc = self.run("rev-parse", "--verify", "--quiet", rev + "^{commit}")
        return proc.stdout.decode().strip() if proc.returncode == 0 else None

    def tree(self, commit):
        proc = self.run("rev-parse", "--verify", "--quiet", commit + ":monocle")
        return proc.stdout.decode().strip() if proc.returncode == 0 else None

    def refs(self):
        remote = [f"refs/remotes/origin/{b}" for b in CANONICAL_BRANCHES if self.resolve(f"refs/remotes/origin/{b}")]
        local = [f"refs/heads/{b}" for b in CANONICAL_BRANCHES if self.resolve(f"refs/heads/{b}")]
        tags = self.out("for-each-ref", "--format=%(refname)", "refs/tags").decode().split()
        return (remote or local) + tags

    def manifest(self, commit):
        listing = self.out("ls-tree", "-r", "-z", "--full-tree", commit, "--", "monocle")
        pending = []
        for record in listing.split(b"\0"):
            if not record:
                continue
            meta, path = record.split(b"\t", 1)
            mode, kind, oid = meta.decode().split()
            parts = path.decode("utf-8").split("/")
            if kind != "blob" or mode == "120000" or parts[-1] in MANIFEST_SKIP_FILES or MANIFEST_SKIP_DIRS & set(parts):
                continue
            pending.append(("./" + "/".join(parts[1:]), oid))
        batch = self.out("cat-file", "--batch", data="".join(f"{oid}\n" for _, oid in pending).encode())
        entries, position = [], 0
        for relative, _ in pending:
            newline = batch.index(b"\n", position)
            size = int(batch[position:newline].split()[2])
            content = batch[newline + 1:newline + 1 + size]
            entries.append((relative, hashlib.sha256(content).hexdigest()))
            position = newline + 1 + size + 1
        return manifest_digest(entries)

    def find_manifest(self, digest, refs):
        commits = self.out("rev-list", f"--max-count={MAX_HISTORY}", *refs, "--", "monocle").decode().split()
        seen = {}
        for commit in commits:
            tree = self.tree(commit)
            if tree not in seen:
                seen[tree] = self.manifest(commit)
            if seen[tree] == digest:
                return commit
        return None


def open_canonical(args):
    """Return (git, description, temp dir or None, whether the source is the canonical repository)."""
    if args.canonical:
        path = Path(args.canonical).resolve()
        git = Git(path)
        if not git.ok("rev-parse", "--git-dir"):
            raise VerifyError(f"{path} is not a git repository")
        origin = git.run("remote", "get-url", "origin").stdout.decode().strip()
        return git, f"local clone {path} (origin {origin or 'none'})", None, normalize_url(origin) == CANONICAL_URL
    temp = tempfile.mkdtemp(prefix="monocle-verify-")
    proc = subprocess.run(["git", "clone", "--quiet", "--no-checkout", CANONICAL_URL + ".git", temp],
                          capture_output=True, env=GIT_ENV, check=False)
    if proc.returncode:
        shutil.rmtree(temp, ignore_errors=True)
        raise VerifyError(f"could not fetch {CANONICAL_URL}: {proc.stderr.decode(errors='replace').strip()}")
    return Git(temp), f"fetched {CANONICAL_URL}", temp, True


def check_provenance(audit, git, refs):
    """Check the attestation against the canonical repository; return the commit whose rules apply."""
    att = audit.attestation
    if not att:
        audit.note("provenance", "attestation", "skip", "no attestation to check against the canonical repository")
        return None
    claimed, digest, dirty = att.get("skill_commit", ""), att.get("skill_sha256", ""), att.get("skill_dirty", "")
    short_refs = ", ".join(ref.split("/")[-1] for ref in refs)
    if COMMIT_RE.match(claimed):
        full = git.resolve(claimed)
        if not full:
            audit.add("provenance", "commit known", False, f"skill_commit {claimed} doesn't exist in the canonical repository")
            return None
        reachable = any(git.ok("merge-base", "--is-ancestor", full, ref) for ref in refs)
        audit.add("provenance", "commit reachable", reachable,
                  f"{full[:12]} {'is' if reachable else 'is not'} on a canonical ref ({short_refs})")
        tree = git.tree(full)
        audit.add("provenance", "tree hash", att.get("skill_tree") == tree,
                  f"attested skill_tree {att.get('skill_tree')}; canonical {full[:12]}:monocle is {tree}")
        canonical_digest = git.manifest(full)
        audit.add("provenance", "content hash", digest == canonical_digest,
                  f"attested skill_sha256 {digest[:16]}…; canonical manifest at {full[:12]} is {canonical_digest[:16]}…")
        audit.add("provenance", "clean tree", dirty == "false",
                  f"skill_dirty: {dirty}; a skill with local edits (for example, an un-upstreamed post-chat-refine) isn't canonical")
        check_context_version(audit, git, full)
        return full
    match = git.find_manifest(digest, refs) if SHA256_RE.match(digest) else None
    audit.add("provenance", "content hash", match is not None,
              f"copied install matches canonical commit {match[:12]}" if match
              else f"skill_sha256 {digest[:16]}… matches no monocle/ tree on {short_refs}")
    check_context_version(audit, git, match)
    return match


def check_context_version(audit, git, commit):
    """A v1 block from a skill commit that already has deployment-context.md hides the context field."""
    if not commit or audit.attestation.get("monocle_attestation") != "v1":
        return
    has_context = git.ok("cat-file", "-e", f"{commit}:{CONTEXT_REFERENCE}")
    audit.add("provenance", "attestation version", not has_context,
              f"v1 attestation, but {commit[:12]} has {CONTEXT_REFERENCE} and writes v2 with deployment_context"
              if has_context else f"v1 attestation; {commit[:12]} predates {CONTEXT_REFERENCE}")


def load_rules(audit, git, commit, ref):
    how = "the report's skill commit"
    if commit is None:
        commit = next(filter(None, (git.resolve(f"refs/{kind}/{ref}") for kind in ("remotes/origin", "heads", "tags"))), None)
        how = f"{ref} tip; the report's skill commit wasn't identified"
        if commit is None:
            raise VerifyError(f"canonical ref {ref!r} not found")
    text = git.out("cat-file", "blob", f"{commit}:monocle/SKILL.md").decode("utf-8")
    audit.rules_source = f"{commit[:12]} ({how})"
    return parse_rules(text)


# ---------------------------------------------------------------- verdict


def decide(audit):
    att = audit.attestation
    if att and not audit.failed("attestation"):
        attested = to_int(att.get("score_final"))
        if audit.reported_final is not None and attested is not None and audit.reported_final > attested:
            return FORGED
        favorable = (audit.reported_final is not None and audit.expected_final is not None
                     and audit.reported_final > audit.expected_final)
        if att.get("skill_dirty") == "false" and favorable and audit.failed("rules", "arithmetic"):
            return FORGED
    if audit.failed("provenance", "rules", "arithmetic", "structure"):
        return WEAKENED
    if audit.failed("attestation"):
        return SUSPECT
    return OFFICIAL


def run_checks(report):
    audit = Audit()
    check_structure(audit, report)
    check_attestation(audit, report)
    check_steering(audit, report)
    return audit


def render(audit, verdict, path):
    order = {"fail": 0, "warn": 1, "skip": 2, "pass": 3}
    lines = [
        f"Report: {path}",
        f"Canonical source: {audit.canonical_source}",
        f"Scoring rules from: {audit.rules_source}",
        f"Mechanical verdict: {verdict}",
        f"Reported score: {label(audit.reported_final, audit.reported_band)}; "
        f"canonical rules give: {label(audit.expected_final, audit.expected_band)}",
        "",
    ]
    for check in sorted(audit.checks, key=lambda c: order[c.status]):
        lines.append(f"[{check.status.upper()}] {check.group}: {check.name} — {check.detail}")
    return "\n".join(lines)


def read_report(path):
    if path == "-":
        data = sys.stdin.buffer.read(MAX_REPORT_BYTES + 1)
    else:
        with open(path, "rb") as handle:
            data = handle.read(MAX_REPORT_BYTES + 1)
    if len(data) > MAX_REPORT_BYTES:
        raise VerifyError(f"report is over {MAX_REPORT_BYTES} bytes")
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError as error:
        raise VerifyError(f"report isn't UTF-8 text: {error}") from error


def verify(args):
    report = Report(read_report(args.report))
    audit = run_checks(report)
    git, source, temp, trusted = open_canonical(args)
    audit.canonical_source = source
    try:
        if not trusted:
            audit.note("provenance", "canonical source", "warn",
                       f"the --canonical clone's origin isn't {CANONICAL_URL}; results are only as good as that clone")
        refs = git.refs()
        if not refs:
            raise VerifyError("canonical repository has no main, development, or tag refs")
        commit = check_provenance(audit, git, refs)
        rules = load_rules(audit, git, commit, args.ref)
        check_score(audit, report, rules)
    finally:
        if temp:
            shutil.rmtree(temp, ignore_errors=True)
    verdict = decide(audit)
    if args.json:
        print(json.dumps({
            "report": args.report,
            "verdict": verdict,
            "canonical_source": audit.canonical_source,
            "canonical_source_trusted": trusted and bool(args.fetch),
            "rules_source": audit.rules_source,
            "reported_score": audit.reported_final,
            "reported_band": audit.reported_band,
            "expected_score": audit.expected_final,
            "expected_band": audit.expected_band,
            "attestation": audit.attestation,
            "checks": [asdict(check) for check in audit.checks],
        }, indent=2, ensure_ascii=False))
    else:
        print(render(audit, verdict, args.report))
    return 0 if verdict == OFFICIAL else 1


# ---------------------------------------------------------------- self-test


def synthetic_report(rules, critical=0, high=1, medium=1, low=2, info=1, nonsec=3,
                     each=None, final=None, attestation=True, dirty="false",
                     version="v2", context="none", line_context=None, context_line=True):
    """Build an in-memory report that follows the Output template."""
    charge = dict(rules.each, **(each or {}))
    counts = {"Critical": critical, "High": high, "Medium": medium, "Low": low, "Info": info}
    ids, findings, number = {}, [], 0
    for sev in SEVERITIES:
        ids[sev] = []
        for _ in range(counts[sev]):
            number += 1
            ids[sev].append(f"S{number}")
            findings.append(f"| S{number} | {SEVERITY_EMOJI[sev]} {sev} | Example finding | `tool.sh:{number}` |")
    rows, total = [], 0
    for sev in SEVERITIES:
        total += counts[sev] * charge[sev]
        rows.append(f"| {SEVERITY_EMOJI[sev]} {sev} | {', '.join(ids[sev]) or '—'} | {counts[sev]} | "
                    f"{charge[sev]} | {counts[sev] * charge[sev]} |")
    nonsec_deduction = min(nonsec * rules.nonsec_each, rules.nonsec_cap)
    total += nonsec_deduction
    rows.append(f"| Non-security | example footguns | {nonsec} | {rules.nonsec_each} (max {rules.nonsec_cap}) | {nonsec_deduction} |")
    rows.append("| Not scored | — | 0 | 0 | 0 |")
    raw = 100 - total
    highest = highest_severity(counts)
    final = rules.clamp(raw, highest) if final is None else final
    clamp = (f"; capped at {final} by the {highest} range" if raw > final
             else f"; floored at {final} by the {highest} range" if max(raw, 0) < final else "")
    band = rules.band(final)
    score = f"{final}/100 ({BAND_EMOJI[band]} {band})"
    risk = highest if highest != "none" else "Info"
    commit = "0123456789abcdef0123456789abcdef01234567"
    shown = line_context or context
    context_text = ("Operator-stated (request, 2026-01-01)" if shown == "operator"
                    else "None supplied — documented-deployment baseline")
    context_lines = [f"{CONTEXT_LINE} {context_text}", ""] if context_line else []
    block = [
        "**Attestation:**", "", "~~~text", f"monocle_attestation: {version}",
        f"skill_repo: {CANONICAL_URL}", f"skill_commit: {commit}", "skill_ref: development",
        f"skill_tree: {'1' * 40}", f"skill_sha256: {'2' * 64}", f"skill_dirty: {dirty}",
        "target: tool.sh (attached file)", "target_ref: attached file",
        f"score_raw: {raw}", f"score_final: {final}", "score_alt: none", f"band: {band}",
        *([f"deployment_context: {context}"] if version == "v2" else []),
        "generated_by: Self-test", "timestamp: 2026-01-01 00:00 UTC", "~~~", "",
    ] if attestation else []
    footer_url = f"{CANONICAL_URL}/tree/{commit}" if attestation else CANONICAL_URL
    return "\n".join([
        "# Monocle Report: tool.sh", "## Monocle Score", "", "<details>",
        f"<summary>Monocle Score: {score} — Approve with conditions</summary>", "",
        f"**Score:** {score} at the documented-deployment baseline — synthetic findings", "",
        f"**Overall risk:** {SEVERITY_EMOJI[risk]} {risk}", "",
        "**Recommendation:** Approve with conditions — synthetic reason", "",
        "**Generated by:** Self-test  ·  **Skill:** monocle", "", *context_lines,
        "| Source | IDs | Count | Each | Deduction |", "|---|---|---|---|---|", *rows, "",
        f"**Total:** 100 − {total} = {raw}{clamp} → **{score}**", "",
        "**Operator baseline:** None — the score doesn't depend on deployment.", "",
        "</details>", "", "---", "", "## Contents", "",
        "- [Monocle Score](#monocle-score)", "- [Security View](#security-view)", "- [Scope](#scope)", "",
        "---", "", "## Security View", "", "<details>",
        f"<summary>Security View: {SEVERITY_EMOJI[risk]} {risk} risk</summary>", "",
        "### Findings", "", "| ID | Severity | Title | Location |", "|----|----------|-------|----------|",
        *findings, "", "</details>", "", "---", "", "## Scope", "", "<details>",
        "<summary>Scope: attached file — 1 file, full coverage</summary>", "",
        "| Field | Value |", "|---|---|", "| **Date** | 2026-01-01 00:00 UTC |",
        "| **Target** | tool.sh (attached file) |", "| **Ref** | attached file |",
        "| **Generated by** | Self-test |", "| **Scope caveats** | None |", "",
        *block, "</details>", "", "---", "", f"[Generated by Monocle]({footer_url})", "",
    ])


def stub_provenance(audit):
    """Stand in for the canonical-repository checks, which need the network."""
    att = audit.attestation
    if not att:
        audit.note("provenance", "attestation", "skip", "no attestation")
        return
    audit.add("provenance", "content hash", True, "self-test stub")
    audit.add("provenance", "clean tree", att.get("skill_dirty") == "false", f"skill_dirty: {att.get('skill_dirty')}")


def self_test():
    skill_dir = Path(__file__).resolve().parents[1]
    repo_root = skill_dir.parent
    rules = parse_rules((skill_dir / "SKILL.md").read_text(encoding="utf-8"))
    problems = []

    cases = (
        ("canonical report", {}, OFFICIAL),
        ("missing attestation", {"attestation": False}, SUSPECT),
        ("local edits disclosed", {"dirty": "true"}, WEAKENED),
        ("lowered Critical deduction", {"critical": 1, "high": 0, "each": {"Critical": rules.each["Critical"] // 2}}, WEAKENED),
        ("raised band limit with a clean attestation", {"critical": 1, "high": 0, "final": rules.ranges["Critical"][1] + 10}, FORGED),
        ("no findings", {"high": 0, "medium": 0, "low": 0, "info": 0, "nonsec": 0}, OFFICIAL),
        ("operator-stated context", {"context": "operator"}, OFFICIAL),
        ("legacy v1 attestation", {"version": "v1", "context_line": False}, OFFICIAL),
        ("v2 without a Deployment context line", {"context_line": False}, WEAKENED),
        ("operator context shown as none", {"context": "operator", "line_context": "none"}, WEAKENED),
    )
    for name, options, expected in cases:
        report = Report(synthetic_report(rules, **options))
        audit = run_checks(report)
        stub_provenance(audit)
        check_score(audit, report, rules)
        verdict = decide(audit)
        if verdict != expected:
            failed = "; ".join(f"{c.group}: {c.name} — {c.detail}" for c in audit.checks if c.status == "fail")
            problems.append(f"{name}: expected {expected}, got {verdict} ({failed or 'no failed checks'})")

    # A v1 block attesting a skill commit that already has deployment-context.md is a downgrade.
    class ContextTree:
        def ok(self, *args):
            return True

    report = Report(synthetic_report(rules, version="v1", context_line=False))
    audit = run_checks(report)
    stub_provenance(audit)
    check_context_version(audit, ContextTree(), "0" * 40)
    check_score(audit, report, rules)
    if decide(audit) != WEAKENED:
        problems.append(f"v1 attestation on a context-aware commit: expected {WEAKENED}, got {decide(audit)}")

    with tempfile.TemporaryDirectory() as temp:
        for relative, content in (("SKILL.md", b"a\n"), ("references/x.md", b"b\n"),
                                  (".DS_Store", b"junk"), ("__pycache__/c.pyc", b"junk")):
            Path(temp, relative).parent.mkdir(parents=True, exist_ok=True)
            Path(temp, relative).write_bytes(content)
        expected_text = "".join(f"{hashlib.sha256(c).hexdigest()}  {p}\n"
                                for p, c in (("./SKILL.md", b"a\n"), ("./references/x.md", b"b\n")))
        if manifest_digest(manifest_entries(temp)) != hashlib.sha256(expected_text.encode()).hexdigest():
            problems.append("manifest: digest doesn't match the documented format")

    # CONTRIBUTING.md: scoring guidance stays consistent across SKILL.md, README.md, and security.md.
    each = rules.each
    spans = ", ".join(f"{sev} {'–'.join(map(str, rules.ranges[sev]))}" for sev in ("Critical", "High", "Medium"))
    spans += f", otherwise {'–'.join(map(str, rules.ranges['none']))}"
    expectations = {
        repo_root / "README.md": [
            f"{each['Critical']} / {each['High']} / {each['Medium']} / {each['Low']} |",
            f"{rules.nonsec_each} each, {rules.nonsec_cap} at most", spans,
            ", ".join(f"{low}–{high} {BAND_EMOJI[name]} {name}" for low, high, name in rules.bands),
        ],
        skill_dir / "references" / "security.md": [
            ", ".join(f"{sev} −{each[sev]}" for sev in ("Critical", "High", "Medium", "Low")) + f", Info {each['Info']}",
            f"({spans})",
        ],
    }
    for path, needles in expectations.items():
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        problems += [f"{path.name}: scoring text out of sync with SKILL.md, expected {needle!r}" for needle in needles if needle not in text]

    for problem in problems:
        print(f"FAIL {problem}")
    print(f"self-test: {len(cases)} verdict cases, context-version downgrade, manifest format, scoring-doc sync — "
          f"{'all passed' if not problems else f'{len(problems)} problem(s)'}")
    return 1 if problems else 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("report", nargs="?", help="Monocle report to verify, or - for stdin")
    source = parser.add_mutually_exclusive_group()
    source.add_argument("--fetch", action="store_true", help=f"clone {CANONICAL_URL} into a temporary directory")
    source.add_argument("--canonical", metavar="DIR", help="use an existing clone of the canonical repository")
    parser.add_argument("--ref", default="development",
                        help="canonical branch or tag whose rules apply when the report's skill commit isn't identified")
    parser.add_argument("--json", action="store_true", help="print machine-readable results")
    parser.add_argument("--manifest", metavar="DIR", help="print the skill_sha256 of a skill directory and exit")
    parser.add_argument("--self-test", action="store_true", help="run the built-in checks and exit")
    args = parser.parse_args(argv)
    try:
        if args.self_test:
            return self_test()
        if args.manifest:
            print(manifest_digest(manifest_entries(args.manifest)))
            return 0
        if not args.report or not (args.fetch or args.canonical):
            parser.error("give a REPORT and either --fetch or --canonical DIR")
        if not REF_RE.match(args.ref):
            parser.error("--ref must be a branch or tag name")
        return verify(args)
    except (VerifyError, OSError) as error:
        print(f"verify_report.py: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
